import './landing.css'
import '../javascripts/modernizr-2.6.2.min'
import '../javascripts/jquery-1.10.2.min'
import '../javascripts/jquery.easing.1.3'
import '../javascripts/bootstrap'
import '../javascripts/owl.carousel.min'
import '../javascripts/jquery.magnific-popup.min'
import '../javascripts/hoverIntent'
import '../javascripts/superfish'
import '../javascripts/easyResponsiveTabs'
import '../javascripts/fastclick'
// import '../javascripts/jquery.parallax-scroll.min'
import '../javascripts/jquery.waypoints.min'
import '../javascripts/main'
